# Версия docker-compose, для которой написан и протестирован данный сценарий
# существенно отличаются мажорные версии 2.х и  3.х, поэтому можно указывать 
# version: "3"
version: "3.7"

# Описание всех контейнеров, которые нужно запустить
services: 
  # Первый контейнер. Это и есть NGINX http сервер Наименование "web" выбрано
  # произвольно и будет использоваться как адрес во внутренней сети docker
  # и ссылка для других контейнеров
  web:
    # Для запуска контейнера необходимо загрузить и запустить именованный 
    # образ "nginx:1.19.0" из регистра по умолчанию (DockerHub)
    image: nginx:1.19.0
    # "Откроем" порт 80 контейнера на порте 8081 хоста. Синтаксис команды:
    # список строк, начинающихся с "-" с парами номеров портов через ":"
    # - <порт хоста>:<порт контейнера>
    #...
    ports:
      - 80:80
    volumes: 
      - ./conf.d:/etc/nginx/conf.d/
      - ./public:/public/

      