version: "3.7"

services:
  # Название контейнера
  aot_builder:
    container_name: "aot_builder"
    # Используем образ
    image: andx2/aqueduct:4.0.0-b1
    # Монтируем папку aqueduct приложения в контейнер /app
    volumes:
      - ./data_app/:/app
      - ./auth_app/:/auth_app
    # Переходим в папку проекта - скачиваем зависимости - собираем билд
    # поскольку папка проекта, фактически смонтирована из хоста, то и
    # сборка будет помещена в хостовую директорию проекта data_app.aot
    # повышаем права файла сборки до "Исполняемый файл"
    # повторяем для auth_app
    command: sh -c "
      (cd /app
      && pub get
      && aqueduct build -d /app/
      && chmod +x data_app.aot)
      && (cd /auth_app
      && pub get
      && aqueduct build -d /auth_app/
      && chmod +x auth_app.aot)
      "
