version: "3.7"

services:
  web:
    ports:
      - 80:80
    volumes:
      - ./conf.dev.d:/etc/nginx/conf.d/
      - ./public:/public/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt

  certbot:
    command: certonly --dry-run --webroot -w /usr/share/nginx/html/letsencrypt -d dartservice.ru

  # Контейнер приложения
  data_app:
    # Команда запуска приложения внутри контейнера
    command: sh -c "cd /app && ./data_app.aot --port 8081 --isolates 6"
    # Политика перезапуска при остановке приложения
    # например при внутренней ошибке
    restart: "no"

  # Контейнер приложения
  auth_app:
    # Команда запуска приложения внутри контейнера
    command: sh -c "cd /auth_app && ./auth_app.aot --port 8082 --isolates 6"
    # Политика перезапуска при остановке приложения
    # например при внутренней ошибке
    restart: "no"

    # Контейнер с DB
  data_db:
    # Порт открываемый для доступа хоста
    ports:
      - "5432:5432"

  # Контейнер с DB авторизации
  auth_db:
    # Порт открываемый для доступа хоста
    ports:
      - "5433:5432"
