name: auth_app
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 4.0.0-b1
  # контейнер DI
  get_it: 4.0.4
  # декларативный кодегенератор для get_it
  injectable: 1.0.4
  # http клиент
  dio: 3.0.10
  # jwt helper
  jose: 0.2.1+1
  # генератор идентификаторов
  uuid: 2.2.2

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: 2.0.0-b1
  # зависимости injectable этапа компиляции
  # использует пакет build_runner
  injectable_generator: 1.0.4
  build_runner: 1.10.0
